# Generated by Django 3.2 on 2022-12-07 03:44

import core.accounts.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('firstname', models.CharField(max_length=100, verbose_name='first name')),
                ('lastname', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=100, unique=True, verbose_name='user name')),
                ('is_active', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('id_verify', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=core.accounts.models.upload_to_image, verbose_name='Imagen')),
                ('enable_notific', models.BooleanField(default=False, verbose_name='Enable Notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Task')),
                ('message', models.TextField(verbose_name='Message')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('recieved_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'Notification',
            },
        ),
    ]
