# Generated by Django 3.2 on 2022-08-20 20:09

import core.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220808_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=core.accounts.models.upload_to_image, verbose_name='Imagen'),
        ),
    ]
