# Generated by Django 3.2 on 2022-07-19 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_title', models.CharField(max_length=255, verbose_name='Search title')),
                ('mont_page', models.PositiveSmallIntegerField(default=1, verbose_name='Mont page')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('create_update', models.DateTimeField(auto_now=True, verbose_name='Date update')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('company', models.CharField(choices=[('amazon', 'amazon'), ('ebay', 'ebay')], default='Amazon', max_length=15)),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searchs',
                'db_table': 'Search',
            },
        ),
        migrations.CreateModel(
            name='LogRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code_request', models.PositiveSmallIntegerField(verbose_name='Status code')),
                ('page', models.PositiveSmallIntegerField(default=1, verbose_name='Pagination')),
                ('url_page', models.URLField(verbose_name='URL page')),
                ('date_request', models.DateTimeField(verbose_name='Date request')),
                ('create_date_log', models.DateTimeField(auto_now_add=True, verbose_name='Date create log')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_scraping.searchusermodel', verbose_name='Search request')),
            ],
            options={
                'verbose_name': 'log request',
                'verbose_name_plural': 'logs requests',
                'db_table': 'Log Request',
            },
        ),
        migrations.CreateModel(
            name='EbayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(default=1, verbose_name='Page')),
                ('product', models.CharField(max_length=255, verbose_name='Product name')),
                ('img', models.URLField(verbose_name='URL image')),
                ('url_product', models.URLField(verbose_name='URL article')),
                ('rate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rate')),
                ('top_rate', models.BooleanField(default=False, verbose_name='Top rate')),
                ('price', models.FloatField(verbose_name='Price')),
                ('old_price', models.FloatField(verbose_name='Before price')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date update')),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_scraping.searchusermodel')),
            ],
            options={
                'verbose_name': 'ebay',
                'verbose_name_plural': 'ebay',
                'db_table': 'Data Ebay',
            },
        ),
        migrations.CreateModel(
            name='AmazonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(default=1, verbose_name='Page')),
                ('product', models.CharField(max_length=255, verbose_name='Product name')),
                ('img', models.URLField(verbose_name='URL image')),
                ('url_product', models.URLField(verbose_name='URL article')),
                ('rate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rate')),
                ('price', models.FloatField(verbose_name='Price')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date update')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_scraping.searchusermodel')),
            ],
            options={
                'verbose_name': 'amazon',
                'verbose_name_plural': 'amazon',
                'db_table': 'Data Amazon',
            },
        ),
    ]
