# Generated by Django 3.2 on 2022-07-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0002_alter_logrequestmodel_search_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrequestmodel',
            name='page',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='pagination'),
        ),
    ]
