# Generated by Django 3.2 on 2022-07-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0002_auto_20220728_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonmodel',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
        migrations.AddField(
            model_name='ebaymodel',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
        migrations.AddField(
            model_name='searchusermodel',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
    ]
