# Generated by Django 3.2 on 2022-08-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0003_auto_20220730_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonmodel',
            name='img',
            field=models.URLField(max_length=500, verbose_name='URL image'),
        ),
        migrations.AlterField(
            model_name='amazonmodel',
            name='url_product',
            field=models.URLField(max_length=500, verbose_name='URL article'),
        ),
        migrations.AlterField(
            model_name='ebaymodel',
            name='img',
            field=models.URLField(max_length=500, verbose_name='URL image'),
        ),
        migrations.AlterField(
            model_name='ebaymodel',
            name='url_product',
            field=models.URLField(max_length=500, verbose_name='URL article'),
        ),
        migrations.AlterField(
            model_name='logrequestmodel',
            name='url_page',
            field=models.URLField(max_length=500, verbose_name='URL page'),
        ),
    ]
