# Generated by Django 3.2 on 2022-07-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0003_logrequestmodel_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(default=1, verbose_name='page')),
                ('product', models.CharField(max_length=255, verbose_name='product name')),
                ('img', models.URLField(verbose_name='URL image')),
                ('url_product', models.URLField(verbose_name='URL article')),
                ('rate', models.CharField(blank=True, max_length=20, null=True, verbose_name='rate')),
                ('top_rate', models.BooleanField(default=False, verbose_name='top rate')),
                ('price', models.FloatField(verbose_name='price')),
                ('old_price', models.FloatField(verbose_name='before price')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('create_update', models.DateTimeField(auto_now=True, verbose_name='date update')),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_scraping.searchusermodel')),
            ],
            options={
                'verbose_name': 'ebay',
                'verbose_name_plural': 'ebay',
                'db_table': 'Data Ebay',
            },
        ),
    ]
