# Generated by Django 3.2 on 2022-10-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0004_auto_20220808_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchusermodel',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Task ID'),
        ),
    ]
