# Generated by Django 3.2 on 2022-07-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0004_ebaymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrequestmodel',
            name='url_page',
            field=models.URLField(default='http://www.amazon.com', verbose_name='URL page'),
            preserve_default=False,
        ),
    ]
