# Generated by Django 3.2 on 2022-07-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0005_logrequestmodel_url_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrequestmodel',
            name='company',
            field=models.CharField(choices=[('amazon', 'amazon'), ('ebay', 'ebay')], default='amazon', max_length=15),
        ),
    ]
