# Generated by Django 3.2 on 2022-11-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0005_searchusermodel_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchusermodel',
            name='status_task',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'SUCCESS'), ('FAILURE', 'FAILURE'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('RECEIVED', 'RECEIVED'), ('REJECTED', 'REJECTED'), ('RETRY', 'RETRY'), ('PENDING', 'PENDING')], default=None, max_length=20, null=True, verbose_name='Status Task'),
        ),
    ]
