# Generated by Django 3.2 on 2022-12-01 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0008_alter_searchusermodel_status_task'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='amazonmodel',
            table='Amazon',
        ),
        migrations.AlterModelTable(
            name='ebaymodel',
            table='Ebay',
        ),
        migrations.CreateModel(
            name='WalmartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(default=1, verbose_name='Page')),
                ('product', models.CharField(max_length=255, verbose_name='Product name')),
                ('img', models.URLField(max_length=500, verbose_name='URL image')),
                ('url_product', models.URLField(max_length=500, verbose_name='URL article')),
                ('rate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rate')),
                ('top_rate', models.BooleanField(default=False, verbose_name='Top rate')),
                ('price', models.FloatField(verbose_name='Price')),
                ('old_price', models.FloatField(verbose_name='Before price')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date update')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_scraping.searchusermodel')),
            ],
            options={
                'verbose_name': 'walmart',
                'verbose_name_plural': 'walmart',
                'db_table': 'Walmart',
            },
        ),
    ]
