# Generated by Django 3.2 on 2022-12-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_scraping', '0009_auto_20221130_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchusermodel',
            name='company',
            field=models.CharField(choices=[('amazon', 'amazon'), ('ebay', 'ebay'), ('etsy', 'etsy'), ('macys', 'macys'), ('walmart', 'walmart')], default='Amazon', max_length=15),
        ),
        migrations.CreateModel(
            name='MacysModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(default=1, verbose_name='Page')),
                ('product', models.CharField(max_length=255, verbose_name='Product name')),
                ('img', models.URLField(max_length=500, verbose_name='URL image')),
                ('url_product', models.URLField(max_length=500, verbose_name='URL article')),
                ('rate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rate')),
                ('top_rate', models.BooleanField(default=False, verbose_name='Top rate')),
                ('price', models.FloatField(verbose_name='Price')),
                ('old_price', models.FloatField(verbose_name='Before price')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date update')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_scraping.searchusermodel')),
            ],
            options={
                'verbose_name': 'macys',
                'verbose_name_plural': 'macys',
                'db_table': 'Macys',
            },
        ),
        migrations.CreateModel(
            name='EtsyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(default=1, verbose_name='Page')),
                ('product', models.CharField(max_length=255, verbose_name='Product name')),
                ('img', models.URLField(max_length=500, verbose_name='URL image')),
                ('url_product', models.URLField(max_length=500, verbose_name='URL article')),
                ('rate', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rate')),
                ('top_rate', models.BooleanField(default=False, verbose_name='Top rate')),
                ('price', models.FloatField(verbose_name='Price')),
                ('old_price', models.FloatField(verbose_name='Before price')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Date update')),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('search', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_scraping.searchusermodel')),
            ],
            options={
                'verbose_name': 'etsy',
                'verbose_name_plural': 'etsy',
                'db_table': 'Etsy',
            },
        ),
    ]
